---
title: "git_01"
author: "Otis Mixon"
date: "October 8th 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.

## First Verse 
`Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.    
He took his vorpal sword in hand:  
Long time the manxome foe he sought --  
So rested he by the Tumtum tree,  
And stood awhile in thought.  

## Second Verse
And, as in uffish thought he stood,  
The Jabberwock, with eyes of flame,  
Came whiffling through the tulgey wood,  
And burbled as it came!  

One, two! One, two! And through and through  
The vorpal blade went snicker-snack!  
He left it dead, and with its head  
He went galumphing back.  


## Third Verse
"And, has thou slain the Jabberwock?  
Come to my arms, my beamish boy!  
O frabjous day! Callooh! Callay!'  
He chortled in his joy.  


## Last Verse
I, Too, Sing America by Langston Hughes

I, too, sing America.  
I am the darker brother.  
They send me to eat in the kitchen  
When company comes,  
But I laugh,  
And eat well,  
And grow strong.  
Tomorrow,  
I'll be at the table  
When company comes.  
Nobody'll dare  
Say to me,  
"Eat in the kitchen,"  
Then.  
Besides,   
They'll see how beautiful I am  
And be ashamed--  

I, too, am America.   
